Pyromod is working! If you like pyromod, please star it at https://github.com/usernein/pyromod
Traceback (most recent call last):
  File "/home/runner/workspace/main.py", line 3, in <module>
    Bot().run()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/methods/utilities/run.py", line 80, in run
    run(self.start())
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot.py", line 32, in start
    await super().start()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/methods/utilities/start.py", line 74, in start
    await self.initialize()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/methods/auth/initialize.py", line 46, in initialize
    self.load_plugins()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/client.py", line 689, in load_plugins
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/workspace/plugins/start.py", line 9, in <module>
    from database.database import present_user, add_user, get_verify_status, update_verify_status
ImportError: cannot import name 'get_verify_status' from 'database.database' (/home/runner/workspace/database/database.py)